### ISSUE TITLE
No module named 'models.loss_func'

### ISSUE THREAD

**Issue by qiunlp** [FFTYYY/RoR_relation_extraction#2]
您好：
当我运行：python main.py --dataset=semeval2018_task7 --auto_hyperparam
错误：File "/home/RoR/models/graph_trans.py", line 7, in <module>
    from .loss_func import *
ModuleNotFoundError: No module named 'models.loss_func'
谢谢！

**Comment by FFTYYY** [comment]
sorry just remove that line pls😂
and note there is a typo in readme, the dataset name should be 'semeval_2018_task7' instead of 'semeval2018_task7 '

anyway, I've updated the repo you can just use the updated version

**Comment by qiunlp** [comment]
谢谢您及时回复。
  问题应该是model目录下缺失  loss_func模块。

**Comment by FFTYYY** [comment]
这其实是一条遗留的早期代码，我后来删掉了loss_func.py文件，但是忘了删除这行代码...

因为我的实验都是在远端服务器上做的，我用的代码同步的工具只会同步文件的修改和新建，不会同步删除，所以如果我删了一个文件，他在远端并不会删除，所以即使这条引用忘记删了也不会报错，以至于这错误一直留着😅

**Comment by qiunlp** [comment]
当我删除from .loss_func import *后，出现
NotADirectoryError: `logs` is not exist.

**Comment by FFTYYY** [comment]
原因是没有初始化fitlog....已经修复了，请同步我最新的提交

**Comment by qiunlp** [comment]
我重下载了您的代码，上述问题还在

**Comment by FFTYYY** [comment]
我这里测试没有问题....
请用命令`git rev-parse HEAD`确认版本号是`593f532ed971f53e07f3c8f338bafb5f503b52e5`
另外请确保调用的指令中包含了`--auto_hyperparam`或`--no_fitlog`
如果还是不行的话，试试手动创建空目录logs：`mkdir logs`

**Comment by qiunlp** [comment]
手动创建空目录logs后就OK了，谢谢您！
