### ISSUE TITLE
为什么在训练的时候只考虑了"COMPARE"关系？

### ISSUE THREAD

**Issue by longlongman** [FFTYYY/RoR_relation_extraction#3]
很有意思的工作，关系的关系，通过transformer来自动寻找关系间的依赖，很有启发，但是我看完代码有一些不太了解的地方，在dataloader_semeval_2018_task7文件的parse_a_key_file函数里有
`		if dtype == "train":
                    if rel == "COMPARE":
		       datas[text_id].ans.append(Relation(ent_b , ent_a , rel))`
这里是只考虑了COMPARE这一种关系吗？如果是这是为什么呢？谢谢。

**Comment by FFTYYY** [comment]
COMPARE是双向关系，但是数据集给的时候只给正向边，这里是把反向关系也加进去。这个数据集里只有COMPARE是双向关系
