### ISSUE TITLE
How to preprocess the dataset ACE 2005 after downloading it from LDC?

### ISSUE THREAD

**Issue by vhientran** [FFTYYY/RoR_relation_extraction#5]
Hi @FFTYYY , thanks for releasing your source code. For the SemEval 2018 Task 7, you guide to use the command: _bash prep_data_and_env.sh_ . I wonder about how to preprocess the ACE_2005 dataset, as I downloaded it from LDC?

**Comment by FFTYYY** [comment]
please use https://github.com/mgormley/ace-data-prep to do pre-processing and put processed json version data into ./data folder. 
you can check config.py for exact folder structure

**Comment by vhientran** [comment]
I understand. Thank you for your help.
